/**
 * AI Service for StudySync
 * This service provides AI-powered features like summarization and flashcard generation.
 * In production, replace the simulated delay and response with actual API calls to Gemini or OpenAI.
 */

const SIMULATED_DELAY = 1500;

export const aiService = {
    /**
     * Summarizes a given text into a concise study note.
     */
    summarize: async (text) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                const words = text.split(' ');
                if (words.length < 50) {
                    resolve("This text is already quite concise, but focused on the core concepts presented in your notes.");
                    return;
                }

                // Simulated AI Summary
                const summary = `### AI Study Summary
This note discusses the core principles of **${words.slice(0, 3).join(' ')}** and related concepts. 

**Key Takeaways:**
1. Unified understanding of the architectural patterns described.
2. Optimization strategies for better academic retention.
3. Summary of practical applications in IT and Computer Science.

*Generated by StudySync AI Assistant - [Mock Implementation]*`;

                resolve(summary);
            }, SIMULATED_DELAY);
        });
    },

    /**
     * Generates a set of flashcards from a given text.
     */
    generateFlashcards: async (moduleName, text) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                const flashcards = [
                    {
                        question: `Main concept of ${moduleName}?`,
                        answer: "The primary framework discussed in your study materials.",
                        level: 1
                    },
                    {
                        question: "What is the most critical definition in this text?",
                        answer: "The technical term defined in the first paragraph of your notes.",
                        level: 1
                    },
                    {
                        question: "How does this apply to real-world scenarios?",
                        answer: "Through the practical implementation steps mentioned in the conclusion.",
                        level: 2
                    }
                ];
                resolve(flashcards);
            }, SIMULATED_DELAY * 1.5);
        });
    },

    /**
     * Generates a 5-question quiz from the given note content.
     */
    generateQuiz: async (content) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                // Mock Quiz Generation based on simple keywords if possible, or generic placeholders
                // In production, send 'content' to an LLM.

                const quiz = [
                    {
                        id: 1,
                        question: "What is the primary topic discussed in these notes?",
                        options: ["Database Optimization", "Frontend State Management", "System Architecture", "Network Security"],
                        correctIndex: 2
                    },
                    {
                        id: 2,
                        question: "Which pattern was highlighted as critical for scalability?",
                        options: ["Singleton", "Observer", "Microservices", "Monolith"],
                        correctIndex: 2
                    },
                    {
                        id: 3,
                        question: "True or False: The text emphasizes manual memory management.",
                        options: ["True", "False"],
                        correctIndex: 1
                    },
                    {
                        id: 4,
                        question: "What is the recommended approach for handling legacy code?",
                        options: ["Refactor immediately", "Wrap in adapters", "Delete and rewrite", "Ignore it"],
                        correctIndex: 1
                    },
                    {
                        id: 5,
                        question: "Which tool was mentioned for monitoring?",
                        options: ["Prometheus", "Grafana", "New Relic", "All of the above"],
                        correctIndex: 3
                    }
                ];
                resolve(quiz);
            }, SIMULATED_DELAY * 1.5);
        });
    }
};

export default aiService;
