import React, { useState } from 'react';
import Layout from '../components/layout/Layout';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Input from '../components/ui/Input';
import { Plus, Trash2, Database, Code, Download, Copy, Table as TableIcon } from 'lucide-react';

const SQLVisualizer = () => {
    const [tables, setTables] = useState([
        {
            id: 't1',
            name: 'Users',
            columns: [
                { name: 'id', type: 'INT', primaryKey: true, autoIncrement: true },
                { name: 'email', type: 'VARCHAR(255)', unique: true },
                { name: 'created_at', type: 'TIMESTAMP', defaultValue: 'CURRENT_TIMESTAMP' }
            ]
        }
    ]);

    const addTable = () => {
        const newTable = {
            id: Date.now().toString(),
            name: 'NewTable',
            columns: [{ name: 'id', type: 'INT', primaryKey: true }]
        };
        setTables([...tables, newTable]);
    };

    const updateTable = (tableId, updates) => {
        setTables(tables.map(t => t.id === tableId ? { ...t, ...updates } : t));
    };

    const addColumn = (tableId) => {
        const table = tables.find(t => t.id === tableId);
        const newColumns = [...table.columns, { name: 'new_col', type: 'VARCHAR(255)' }];
        updateTable(tableId, { columns: newColumns });
    };

    const deleteColumn = (tableId, colIndex) => {
        const table = tables.find(t => t.id === tableId);
        const newColumns = [...table.columns];
        newColumns.splice(colIndex, 1);
        updateTable(tableId, { columns: newColumns });
    };

    const generateSQL = () => {
        let sql = '-- Generated by StudySync SQL Visualizer\n\n';
        tables.forEach(table => {
            sql += `CREATE TABLE ${table.name} (\n`;
            table.columns.forEach((col, idx) => {
                let line = `  ${col.name} ${col.type}`;
                if (col.primaryKey) line += ' PRIMARY KEY';
                if (col.autoIncrement) line += ' AUTOINCREMENT';
                if (col.unique) line += ' UNIQUE';
                if (col.defaultValue) line += ` DEFAULT ${col.defaultValue}`;

                sql += line + (idx === table.columns.length - 1 ? '' : ',') + '\n';
            });
            sql += ');\n\n';
        });
        return sql;
    };

    const handleCopySQL = () => {
        navigator.clipboard.writeText(generateSQL());
        alert('SQL copied to clipboard!');
    };

    return (
        <Layout title="SQL Schema Visualizer">
            <div className="flex justify-between items-center mb-8">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">Database Architect</h1>
                    <p className="text-slate-500 dark:text-slate-400">Design your schema visually and generate production-ready SQL.</p>
                </div>
                <div className="flex gap-3">
                    <Button variant="secondary" onClick={handleCopySQL} className="flex items-center gap-2">
                        <Copy size={18} />
                        <span>Copy SQL</span>
                    </Button>
                    <Button onClick={addTable} className="flex items-center gap-2">
                        <Plus size={20} />
                        <span>Add Table</span>
                    </Button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <div className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
                    {tables.map(table => (
                        <div key={table.id} className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden animate-in fade-in zoom-in-95">
                            <div className="bg-slate-50 dark:bg-slate-800/50 p-4 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center">
                                <div className="flex items-center gap-2">
                                    <TableIcon size={18} className="text-primary-500" />
                                    <input
                                        className="bg-transparent font-bold text-slate-800 dark:text-slate-100 outline-none focus:ring-1 focus:ring-primary-500/20 rounded px-1 w-32"
                                        value={table.name}
                                        onChange={(e) => updateTable(table.id, { name: e.target.value })}
                                    />
                                </div>
                                <button onClick={() => setTables(tables.filter(t => t.id !== table.id))} className="text-slate-300 hover:text-red-500">
                                    <Trash2 size={16} />
                                </button>
                            </div>
                            <div className="p-4 space-y-3">
                                {table.columns.map((col, idx) => (
                                    <div key={idx} className="flex items-center gap-2 text-xs">
                                        <input
                                            className="flex-1 bg-slate-50 dark:bg-slate-800 border border-slate-100 dark:border-slate-700 rounded px-2 py-1 outline-none text-slate-700 dark:text-slate-300"
                                            value={col.name}
                                            onChange={(e) => {
                                                const newCols = [...table.columns];
                                                newCols[idx].name = e.target.value;
                                                updateTable(table.id, { columns: newCols });
                                            }}
                                        />
                                        <select
                                            className="w-24 bg-slate-50 dark:bg-slate-800 border border-slate-100 dark:border-slate-700 rounded px-1 py-1 outline-none text-slate-500"
                                            value={col.type}
                                            onChange={(e) => {
                                                const newCols = [...table.columns];
                                                newCols[idx].type = e.target.value;
                                                updateTable(table.id, { columns: newCols });
                                            }}
                                        >
                                            <option>INT</option>
                                            <option>VARCHAR(255)</option>
                                            <option>TEXT</option>
                                            <option>BOOLEAN</option>
                                            <option>TIMESTAMP</option>
                                            <option>DECIMAL(10,2)</option>
                                        </select>
                                        <button onClick={() => deleteColumn(table.id, idx)} className="text-slate-300 hover:text-red-400">
                                            <Trash2 size={14} />
                                        </button>
                                    </div>
                                ))}
                                <button
                                    onClick={() => addColumn(table.id)}
                                    className="w-full py-2 border border-dashed border-slate-200 dark:border-slate-700 rounded-xl text-[10px] uppercase font-bold text-slate-400 hover:border-primary-500 hover:text-primary-500 transition-all"
                                >
                                    + Add Column
                                </button>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="lg:col-span-1">
                    <Card title="Generated SQL Script" HeaderAction={<Code size={18} className="text-slate-400" />}>
                        <div className="bg-slate-900 rounded-2xl p-4 font-mono text-[11px] text-slate-100 min-h-[400px] shadow-inner overflow-x-auto">
                            <pre><code>{generateSQL()}</code></pre>
                        </div>
                        <div className="mt-4 p-4 bg-primary-50 dark:bg-primary-900/10 rounded-2xl border border-primary-100 dark:border-primary-800">
                            <h4 className="text-xs font-black text-primary-700 dark:text-primary-300 uppercase tracking-widest mb-2">Pro Tip</h4>
                            <p className="text-[11px] text-slate-600 dark:text-slate-400 leading-relaxed">
                                Always include an <strong>id</strong> field with <strong>PRIMARY KEY</strong> for efficient indexing and relationship mapping.
                            </p>
                        </div>
                    </Card>
                </div>
            </div>
        </Layout>
    );
};

export default SQLVisualizer;
